name: FastAPI CI

on: 
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3
    
      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
    
      # 3. Instalar dependencias
                # Si tengo entorno virtual con python -m venv .env, pip y requirements.txt
                #- name: Install dependencies
                #    run: |
                #    python -m pip install --upgrade pip
                #    pip install -r requirements.txt
      - name: Install dependencies with uv
        run: |
          pip install uv
          uv sync
    
    
      # 4. Correr tests (ajusta según tu framework de testing) Si no uso uv sacar uv run
      - name: Run tests
        run: |
          uv run pytest --maxfail=1 --disable-warnings -q
    
      # 5. Validar que la app arranque (opcional) Si no uso uv sacar uv run
      - name: Check FastAPI startup
        run: |
          uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
          sleep 5
          curl -f http://127.0.0.1:8000/docs
      # 6. Build Docker image
      - name: Build Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: rafacba/ghactions
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}